### ISSUE TITLE
Binding Migration

### ISSUE THREAD

**Issue by matchews** [maggu2810/openhab-dev-doc#1]
I hope I'm posting this in the correct place.  I had a perfectly good Eclipse IDE until I inadvertently let Eclipse perform some updates, which broke everything.  I have reinstalled eclipse in a fresh Windows 10 VM using the instructions here...

https://www.openhab.org/docs/developer/ide/eclipse.html

I then checked out a random binding, imported it into Eclipse, added it to the BND run requirements, resolved the dependencies and everything then worked as expected.

My next step was to import my binding in development, (which was previously working) and converted it to Maven + BND using the instructions here...

https://github.com/maggu2810/openhab-dev-doc/blob/master/maven-bnd.md

The only thing that seemed strange was the path on step 12 is different in my setup...

...\openhab-master\git\openhab2-addons\features\openhab-addons\target\feature\feature.xml

I rebuilt everything in the openhab-addons directory successfully

mvn clean install -DskipChecks -DskipTests -o

Clean/Rebuild Eclipse, then added the new binding to BND run requirements and can't seem to get it to resolve.  I've added the dependencies it is asking for from my binding to the POM, yet it is asking for others that are part of the demo app.  I've been searching for answers and trying different things, but can't seem to get past this.  If I close out my binding, the resolve command will complete successfully.  Any help you can offer would be greatly appreciated.

**pom.xml**

  <dependencies>
<dependency>
    <groupId>com.google.collections</groupId>
    <artifactId>google-collections</artifactId>
    <version>1.0</version>
</dependency>
<dependency>
    <groupId>org.eclipse.platform</groupId>
    <artifactId>org.eclipse.equinox.metatype</artifactId>
    <version>1.5.0</version>
</dependency>
<dependency>
    <groupId>org.objectweb.asm</groupId>
    <artifactId>com.springsource.org.objectweb.asm</artifactId>
    <version>3.2.0</version>
</dependency>
<dependency>
    <groupId>org.eclipse.equinox</groupId>
    <artifactId>org.eclipse.osgi.util</artifactId>
    <version>3.5.2</version>
</dependency>
<dependency>
    <groupId>org.apache</groupId>
    <artifactId>httpclient</artifactId>
    <version>3.0.1</version>
</dependency>
  </dependencies>
  
**Resolve Errors**

Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.elkm1)
          ⇒ [org.openhab.binding.elkm1 version=2.5.0.201907021101]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.apache.http.client.methods))
    [net.minidev.accessors-smart version=1.2.0]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=5.0.0)(!(version>=6.0.0))))
    [org.openhab.transform.bin2json version=2.5.0.201907012137]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.igormaznitsa.jbbp))
    [org.openhab.core.test version=2.5.0.201906270302]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.junit))
    [org.openhab.binding.harmonyhub version=2.5.0.201907012130]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.digitaldan.harmony)(&(version>=1.1.0)(!(version>=2.0.0))))
    [org.openhab.transform.jinja version=2.5.0.201907012138]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hubspot.jinjava))
    [org.openhab.binding.smartmeter version=2.5.0.201907012135]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=io.reactivex)(&(version>=2.2.0)(!(version>=3.0.0))))
    [org.apache.aries.jpa.container version=2.7.0]
      ⇒ osgi.service: (objectClass=javax.persistence.spi.PersistenceProvider)

**Comment by maggu2810** [comment]
That's not the correct place. Sorry

This is a private repo of my own and no official openHAB stuff.

Perhaps you question should be placed to the openHAB Community board.
